// <auto-generated />
using System;
using Catchlogr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catchlogr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatchlogrDbContext))]
    [Migration("20260823164805_AddFishingTripMoonPhase")]
    partial class AddFishingTripMoonPhase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catchlogr.Domain.Entities.Catch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CaughtAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Depth")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LastModified");

                    b.HasIndex("TripId");

                    b.ToTable("Catches");
                });

            modelBuilder.Entity("Catchlogr.Domain.Entities.FishingTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AirTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MoonPhase")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("PressureHpa")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WaterTemp")
                        .HasColumnType("double precision");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("WeatherProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("WeatherSampleTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WindDirectionDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMps")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LastModified");

                    b.ToTable("FishingTrips");
                });

            modelBuilder.Entity("Catchlogr.Domain.Entities.Catch", b =>
                {
                    b.HasOne("Catchlogr.Domain.Entities.FishingTrip", null)
                        .WithMany("Catches")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Catchlogr.Domain.ValueObjects.Bait", "Bait", b1 =>
                        {
                            b1.Property<Guid>("CatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int?>("LengthMm")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int?>("Type")
                                .HasColumnType("integer");

                            b1.Property<int?>("WeightGrams")
                                .HasColumnType("integer");

                            b1.HasKey("CatchId");

                            b1.ToTable("Catches");

                            b1.WithOwner()
                                .HasForeignKey("CatchId");
                        });

                    b.Navigation("Bait");
                });

            modelBuilder.Entity("Catchlogr.Domain.Entities.FishingTrip", b =>
                {
                    b.Navigation("Catches");
                });
#pragma warning restore 612, 618
        }
    }
}
